version: '3'
services:
  web:
    container_name: container-django-single-view
    image: django-single-view
    build:
      context: .
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app:z
    env_file:
      - ./.docker.env
    ports:
      - "8000:8000"
    command: python3 manage.py runserver 0.0.0.0:8000

  db:
    container_name: container-postgres
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.docker.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U sv" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
