#!/usr/bin/env bash
set -o errexit
set -o pipefail
set -o nounset

if [ -z "${DB_USER}" ]; then
    base_postgres_image_default_user='postgres'
    export DB_USER="${base_postgres_image_default_user}"
fi
export DATABASE_URL="postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}"

postgres_ready() {
python << END
import sys

import psycopg2

try:
    connection = psycopg2.connect(
        dbname="${DB_NAME}",
        user="${DB_USER}",
        password="${DB_PASSWORD}",
        host="${DB_HOST}",
        port="${DB_PORT}",
    )
except psycopg2.OperationalError:
    sys.exit(-1)
sys.exit(0)

END
}
until postgres_ready; do
  >&2 echo 'Waiting for PostgreSQL to become available...'
  sleep 1
done
>&2 echo 'PostgreSQL is available'

python3 /app/manage.py flush --no-input
python3 /app/manage.py makemigrations
python3 /app/manage.py migrate

# fill DB
python3 /app/manage.py import_music_works works_metadata.csv

exec "$@"
