# Generated by Django 3.1 on 2020-08-29 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MusicWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iswc', models.CharField(default=None, max_length=30, verbose_name='ISWC')),
                ('title', models.CharField(default=None, max_length=30)),
                ('authors', models.ManyToManyField(to='sv.Author')),
            ],
        ),
        migrations.DeleteModel(
            name='MusicWorkModel',
        ),
    ]
