# Generated by Django 3.1 on 2020-08-30 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sv', '0002_auto_20200829_1951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='author',
            name='last_name',
        ),
        migrations.AddField(
            model_name='author',
            name='name',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='musicwork',
            name='title',
            field=models.CharField(default=None, max_length=128),
        ),
    ]
