# Generated by Django 3.1 on 2020-08-30 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sv', '0003_auto_20200830_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicwork',
            name='iswc',
            field=models.CharField(default=None, max_length=30, null=True, verbose_name='ISWC'),
        ),
        migrations.AlterField(
            model_name='musicwork',
            name='title',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
    ]
